apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMaps.name.env_config}}
data:
  {{ range $path, $files := .Files.Glob "configmap/env" }}
  {{ $name := base $path }}
  {{$name}} : |-
    {{ range $.Files.Lines $path }}{{.}}
    {{ end }}
  {{ end }}