apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMaps.name.php_config}}
data:
  {{- $files := .Files }}
  {{- range tuple "../configmap/php.ini" }}
  {{ . }}: "{{ range $files.Lines . }}{{.}}\n{{ end }}"
  {{- end}}