apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytelweb-deployment
  labels:
    {{.Values.labels.key}}: {{.Values.labels.value}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{.Values.labels.key}}: {{.Values.labels.value}}
  template:
    metadata:
      labels:
        {{.Values.labels.key}}: {{.Values.labels.value}}
    spec:      
      containers:
      - name: mytelweb
        image: {{.Values.image.repository}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ports:
        - containerPort: {{.Values.service.port}}
          name: http
        volumeMounts:
        - name: nginx-config-volume
          mountPath: {{.Values.volumeMountsMap.mount_nginx_config}}
        - name: env-config-volume
          mountPath: {{.Values.volumeMountsMap.mount_env_config}}        
        - name: fpm-pool-config-volume
          mountPath: {{.Values.volumeMountsMap.mount_fpm_pool_config}}
        - name: php-config-volume
          mountPath: {{.Values.volumeMountsMap.mount_php_config}}
          subPath: custom.ini
        - name: supervisord-config-volume
          mountPath: {{.Values.volumeMountsMap.mount_supervisord_config}}       
        resources:
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
        
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{.Values.configMaps.name.nginx_config}}
      - name: env-config-volume
        configMap:
          name: {{.Values.configMaps.name.env_config}}
      - name: fpm-pool-config-volume
        configMap:
          name: {{.Values.configMaps.name.fpm_pool_config}}
      - name: php-config-volume
        configMap:
          name: {{.Values.configMaps.name.php_config}}
      - name: supervisord-config-volume
        configMap:
          name: {{.Values.configMaps.name.supervisord_config}}