#Chi sua gia tri, khong thay doi key
# So luong pod duoc tao
replicaCount: 1

# khai bao label
labels:
  key: app
  value: mytel-website

# Khai bao service
service:
  type: NodePort
  nodePort: 8065
  port: 8080

# Khai bao hostnames
hostAliases:
- ip: 10.201.214.10
  hostnames:
    - apis-uat.mytelpay.com.mm

- ip: 10.201.212.9
  hostnames:
    - mpg.mytel.com.mm

- ip: 10.201.212.201
  hostnames:
    - identity.mytel.com.mm

# Khai bao su dung configmap
configMaps:
  name:
    nginx_config: nginx-config
    env_config: env-config
    fpm_pool_config: fpm-pool-config
    php_config: php-config
    supervisord_config: supervisord-config
# Khai bao su dung PVC
pvc: false
namePVC:
  data:
    name: pvc_uploads
  logs:
    name: pvc_logs
sizePVC:
  data: 100Gi
  logs: 100Gi
   
# Khai bao volumeMount
volumeMountsMap:
  env: dev
  mount_nginx-config: /etc/nginx/
  mount_env-config: /var/www/html/
  mount_fpm-pool-config: /etc/php7/php-fpm.d/www.conf/
  mount_php-config: /etc/php7/conf.d/
  mount_supervisord-config: /etc/supervisor/conf.d/
  mountPathpodinfo: /deployment/podinfo   
  mountPathPVC_data: /var/www/html/public/uploads/
  mountPathPVC_logs: /var/www/html/storage/logs/



# khai bao storageClass
storageClassName: 
  nfs:
    name: sc_nfs
  
#Khai bao tai nguyen su dung cho pod
resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 0.5Gi

# Khai bao promethus
promethus: false
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /actuator/prometheus
  prometheus.io/port: "8881"
  
# Khai bao HealthCheck
healthCheck: false
startupProbe:
  failureThreshold: 10
  httpGet:
    path: /fpm-ping
    port: 8080
    scheme: HTTP
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 2
livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /fpm-ping
    port: 8080
    scheme: HTTP
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 2
readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /fpm-ping
    port: 8080
    scheme: HTTP
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 2

# Khai bao bien moi truong 
ENV_PROFILE: dev
JVM_OPTS: -Xms512m -Xmx2048m -Dsun.net.http.retryPost=false -Dhttp.retryPost=false
  
# Chi dinh pod chay tren node co dinh(chi dung tren live: default hoac abc)
nodeName: 

# So lan deploy Helm
numberHelm: H1

# Thong tin image
image:
  repository: php:7.4-fpm
  pullPolicy: Always

# Khai bao secret-registry harbor
imagePullSecrets:
  name: harbor-secret-registry
#Khai bao IP gluster
glusterfs: false
gluster:
  - 10.201.213.35
  - 10.201.213.36
# Khai bao Volume cluster
glustermap: 
  endpoints: xxxx-service
  path: x-xxx
  pathinpod: /mnt/glusterfs